### PR TITLE
test report types

### LINKED ISSUE #146: Clean up pkg/test/report_test.go
report_test.go duplicate tests done in command_test.go, mostly emulating what command.go is doing, but it does test cover all the code.

We need to:
- remove duplicate tests and test only the behavior of the report types, focusing on the stuff that is easy to break.
- add missing tests

summary:
- add passed test
- add failed test
- add canceled test
- add skipped test
- string
- marshaling

step:
- add passed step
- add failed step
- add canceled step
- add skipped step
- add passed test
- add failed test
- add canceled test
- add skipped test
- marshaling
- equal

report:
- add passed step
- add failed step
- add canceled step
- add skipped step
- marshaling
- equal

### PR DESCRIPTION
**Pull request by parikshithb**
This pr adds unit tests for different report types like report, step and summary and covering their methods and also remove duplicate tests done in command_test.go

Fixes #146

### CODE REVIEW

File: pkg/test/report_test.go [hunk 1]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	}
+
+	r.AddStep(step)
+
+	if len(r.Steps) != 1 {
+		t.Fatalf("Expected 1 step, got %d", len(r.Steps))
+	}
+	if r.Steps[0] != step {
+		t.Errorf("Expected step reference to match")
+	}
```
Comment (nirs) [inline pkg/test/report_test.go:668]: Maybe compare the r.Steps with expected value?

    slices.Equal(r.Steps, []*Step{step})

This compare both the length and the content.

File: pkg/test/report_test.go [hunk 2]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	fakeTime(t)
+	r := newReport("test-command", config)
+
+	step := &Step{
+		Name:     "passed-step",
+		Status:   Passed,
+		Duration: 1.5,
+	}
+
+	r.AddStep(step)
```
Comment (nirs) [inline pkg/test/report_test.go:661]: We can make this more dense, this is trivial code:

	fakeTime(t)
	r := newReport("test-command", config)
    step := &Step{Name: "passed-step", Status: Passed, Duration: 1.5}
    r.AddStep(step)

Separating the validation looks good, I probably need to do the same in commmand_test.go.

File: pkg/test/report_test.go [hunk 3]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	}
+	if r.Steps[0] != step {
+		t.Errorf("Expected step reference to match")
+	}
+	if r.Duration != 1.5 {
+		t.Errorf("Expected duration 1.5, got %f", r.Duration)
+	}
+	if r.Status != Passed {
+		t.Errorf("Expected status %s, got %s", Passed, r.Status)
+	}
```
Comment (nirs) [inline pkg/test/report_test.go:674]: Keeping these as is looks good, if we compare the entire report will have to include also the common fields and config which are not related to this test.

File: pkg/test/report_test.go [hunk 4]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		Name:     "failed-step",
+		Status:   Failed,
+		Duration: 2.0,
+	}
+
+	r.AddStep(step)
+
+	if len(r.Steps) != 1 {
+		t.Fatalf("Expected 1 step, got %d", len(r.Steps))
+	}
```
Comment (nirs) [inline pkg/test/report_test.go:692]: We can replace this with comparing r.Steps with expected value like in the previous test.

File: pkg/test/report_test.go [hunk 5]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	if r.Duration != 2.0 {
+		t.Errorf("Expected duration 2.0, got %f", r.Duration)
+	}
```
Comment (nirs) [inline pkg/test/report_test.go:695]: Since we have separate test for duration, maybe remove it from the tests adding a step?

File: pkg/test/report_test.go [hunk 6]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	// Create a tests step with test items
+	testsStep := &Step{
+		Name:     TestsStep,
+		Status:   Passed,
+		Duration: 5.0,
+		Items: []*Step{
+			{Name: "test1", Status: Passed, Duration: 1.0},
+			{Name: "test2", Status: Failed, Duration: 2.0},
+			{Name: "test3", Status: Skipped, Duration: 0.5},
+			{Name: "test4", Status: Canceled, Duration: 1.5},
```
Comment (nirs) [inline pkg/test/report_test.go:839]: The tests are run in parallel, so the duration should of the step should be 2.0.

File: pkg/test/report_test.go [hunk 7]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	r1.Status = Passed
+	r1.Duration = 3.5
+	r1.Steps = []*Step{
+		{
+			Name:     "step1",
+			Status:   Passed,
+			Duration: 1.5,
+			Items: []*Step{
+				{Name: "subitem1", Status: Passed, Duration: 0.5},
+				{Name: "subitem2", Status: Passed, Duration: 1.0},
```
Comment (nirs) [inline pkg/test/report_test.go:964]: I would add 1.0 duration to all tests to make it easier to understand the values.

File: pkg/test/report_test.go [hunk 8]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	if r1.Equal(r10) {
+		t.Error("Reports with different step content should not be equal")
+	}
+
+}
+
+func TestReportMarshaling(t *testing.T) {
+	fakeTime(t)
+	r1 := newReport("test-command", config)
+	r1.Status = Passed
```
Comment (nirs) [inline pkg/test/report_test.go:955]: If we have a failed step the report should be Failed.

File: pkg/test/report_test.go [hunk 9]
```diff
@@ -648,6 +648,62 @@ func TestReportCleanAllPassed(t *testing.T) {
 	checkRoundtrip(t, r)
 }
 
+func TestSummaryString(t *testing.T) {
+	summary := Summary{
+		Passed:   5,
+		Failed:   2,
+		Skipped:  3,
+		Canceled: 1,
+	}
```
Comment (nirs) [inline pkg/test/report_test.go:1435]: I would keep this in single line, it is simple enough.

File: pkg/test/report_test.go [hunk 10]
```diff
@@ -648,6 +648,62 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	var unmarshaledSummary Summary
+	err = yaml.Unmarshal(bytes, &unmarshaledSummary)
+	if err != nil {
+		t.Fatalf("Failed to unmarshal Summary: %v", err)
+	}
+
+	if unmarshaledSummary.Passed != 4 || unmarshaledSummary.Failed != 3 ||
+		unmarshaledSummary.Skipped != 2 || unmarshaledSummary.Canceled != 1 {
+		t.Errorf("Unmarshaled summary doesn't match original: got %+v", unmarshaledSummary)
+	}
```
Comment (nirs) [inline pkg/test/report_test.go:1465]: Why not compare to the original summary?

    if unmarshaledSummary != summary

File: pkg/test/report_test.go [hunk 11]
```diff
@@ -648,6 +648,456 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		Name: "root",
+	}
+
+	cephfsTest := &Test{
+		TestContext: &Context{name: "passing_test"},
+		Config: &types.TestConfig{
+			Workload: "deploy",
+			Deployer: "appset",
+			PVCSpec:  "cephfs",
+		},
```
Comment (nirs) [inline pkg/test/report_test.go:990]: Lets &config.Tests[0], unless repeating the values here helps to understand the test.

File: pkg/test/report_test.go [hunk 12]
```diff
@@ -648,6 +648,456 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		t.Errorf("Expected status %s, got %s", Passed, addedTest.Status)
+	}
+	if addedTest.Duration != 1.5 {
+		t.Errorf("Expected duration 1.5, got %f", addedTest.Duration)
+	}
+
+	// Verify that parent status was set to Passed (as it was empty before)
+	if rootStep.Status != Passed {
+		t.Errorf("Expected root step status to be %s, got %s", Passed, rootStep.Status)
+	}
```
Comment (nirs) [inline pkg/test/report_test.go:1025]: We can compare rootStep with expected step instead of the manual compares. Same for other step tests.

**Review by nirs — COMMENTED** [review]
Nice!

Did initial review, will look again after the next push.

File: pkg/test/report_test.go [hunk 13]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	r.AddStep(testsStep)
+
+	expectedSummary := Summary{Passed: 1, Failed: 1, Skipped: 1, Canceled: 1}
+	if r.Summary != expectedSummary {
+		t.Errorf("expected summary %+v, got %+v", expectedSummary, r.Summary)
+	}
+}
+
+//nolint:gocritic
+func TestReportEqual(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (parikshithb) [reply pkg/test/report_test.go:804]: since comparing report to itself:
```
dupArg: suspicious method call with the same argument and receiver (gocritic)
		if !baseReport.Equal(baseReport) {
		    ^
1 issues:
* gocritic: 1
```

File: pkg/test/report_test.go [hunk 14]
```diff
@@ -648,6 +648,334 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+
+	r.AddStep(testsStep)
+
+	expectedSummary := Summary{Passed: 1, Failed: 1, Skipped: 1, Canceled: 1}
+	if r.Summary != expectedSummary {
+		t.Errorf("expected summary %+v, got %+v", expectedSummary, r.Summary)
+	}
+}
+
+//nolint:gocritic
```
[the remark this answers is not in the document]
Comment (parikshithb) [reply pkg/test/report_test.go]: since comparing report to itself:
```
dupArg: suspicious method call with the same argument and receiver (gocritic)
		if !baseReport.Equal(baseReport) {
		    ^
1 issues:
* gocritic: 1
```

[the remark this answers is not in the document]
Comment (nirs) [reply pkg/test/report_test.go]: A comment near the linter line will help, like we have in ramen/e2e.

File: pkg/test/report_test.go [hunk 15]
```diff
@@ -648,6 +648,51 @@ func TestReportCleanAllPassed(t *testing.T) {
 	checkRoundtrip(t, r)
 }
 
+func TestSummaryString(t *testing.T) {
+	summary := Summary{Passed: 5, Failed: 2, Skipped: 3, Canceled: 1}
+
+	expectedSummary := "5 passed, 2 failed, 3 skipped, 1 canceled"
```
Comment (nirs) [inline pkg/test/report_test.go:739]: expectedString is a better name.

File: pkg/test/report_test.go [hunk 16]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	expectedStep := &Step{
+		Name:   "root",
+		Status: Passed,
+		Items: []*Step{
+			{
+				Name:     "passing_test",
+				Status:   Passed,
+				Duration: 6.0,
+				Config:   &config.Tests[0],
+				Items:    passedTest.Steps,
```
Comment (nirs) [inline pkg/test/report_test.go:397]: Should we use passTest.xxx for all properties? This This avoid the need to compare the values with the test.

File: pkg/test/report_test.go [hunk 17]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		Duration:    0.5,
+		Steps: []*Step{
+			{Name: "deploy", Status: Canceled, Duration: 0.5},
+		},
+	}
+	rootStep.AddTest(canceledTest)
+
+	expectedStep := &Step{
+		Name: "root",
+		// Failed status should be overridden with Canceled
```
Comment (nirs) [inline pkg/test/report_test.go:456]: This is good thing to test. But I think we have a bug and basically the last test results set the step test. So if one test is canceled and the next test is failed, we will treat the step as failed instead of cancelled.

Lets add a test for this ensuring that canceled state is not affected by failing test after the first tests was cancelled.

File: pkg/test/report_test.go [hunk 18]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+			t.Errorf("rootStep %+v doesn't match expectedStep %+v", rootStep, expectedStep)
+		}
+	})
+
+	// Test with existing Failed status
+	t.Run("FailedInitialStatus", func(t *testing.T) {
+		rootStep := &Step{
+			Name:   "root",
+			Status: Failed,
+		}
```
Comment (nirs) [inline pkg/test/report_test.go:499]: Lets keep very simple object in the same line.

File: pkg/test/report_test.go [hunk 19]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+func TestStepAddMultipleTests(t *testing.T) {
+	rootStep := &Step{Name: "root"}
+
+	// Add multiple tests in sequence with Passed, Skipped and Failed status
+	passedTest := &Test{TestContext: &Context{name: "test1"}, Status: Passed, Duration: 1.0}
+	rootStep.AddTest(passedTest)
+	skippedTest := &Test{TestContext: &Context{name: "test2"}, Status: Skipped, Duration: 0.0}
+	rootStep.AddTest(skippedTest)
+	failedTest := &Test{TestContext: &Context{name: "test3"}, Status: Failed, Duration: 2.0}
+	rootStep.AddTest(failedTest)
```
Comment (nirs) [inline pkg/test/report_test.go:526]: Do we test here something that was not tested in the previous tests?

File: pkg/test/report_test.go [hunk 20]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		},
+		{
+			name: "Different name",
+			a:    step1,
+			b: &Step{
+				Name:     "different",
+				Status:   Passed,
+				Duration: 1.0,
+				Config:   &config.Tests[0],
+			},
```
Comment (nirs) [inline pkg/test/report_test.go:604]: Any reason only this step is using multiple lines? It looks same as next steps.

File: pkg/test/report_test.go [hunk 21]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+	}
+
+	tests := []struct {
+		name  string
+		a     *Step
+		b     *Step
+		equal bool
+	}{
+		{
+			name:  "Self equal",
```
Comment (nirs) [inline pkg/test/report_test.go:585]: Lets use lower case name. Maybe "equal to self" for this one, consistent with "equal to nil".

File: pkg/test/report_test.go [hunk 22]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+			a:     step1,
+			b:     step1,
+			equal: true,
+		},
+		{
+			name:  "Equal to nil",
```
Comment (nirs) [inline pkg/test/report_test.go:591]: But this is actually "not equal to nil"

File: pkg/test/report_test.go [hunk 23]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+
+	tests := []struct {
+		name  string
+		a     *Step
+		b     *Step
+		equal bool
+	}{
+		{
+			name:  "Self equal",
+			a:     step1,
```
Comment (nirs) [inline pkg/test/report_test.go:586]: a: is almost always the same step.

File: pkg/test/report_test.go [hunk 24]
```diff
@@ -651,6 +651,373 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			result := tt.a.Equal(tt.b)
+			if result != tt.equal {
+				t.Errorf("step Equal() = %v, want %v", result, tt.equal)
+			}
+		})
```
Comment (nirs) [inline pkg/test/report_test.go:732]: I'm not sure that table based tests is helpful. For every test we define:

- name
- a
- b
- equal

And only think we share is the check:

			result := tt.a.Equal(tt.b)
			if result != tt.equal {
				t.Errorf("step Equal() = %v, want %v", result, tt.equal)
			}

We could have more clear tests by adding a sub test for every case.

```go
func TestStepEqual(t *testing.T) {
    a := Step{...}

    // Test using a
    t.Run("equal to self", func(t *testing.T) {
        if !a.Equal(a) {
            t.Fatalf(...)
        }
    })

    // Test creating b
    t.Run("equal to other", func(t *testing.T) {
        b := Step{...}
        if !a.Equal(b) {
            t.Fatalf(...)
        }
    })

    // Test creating a and b
    t.Run("both nil config", func(t *testing.T) {
        a := Step{...}
        b := Step{...}
        if !a.Equal(b) {
            t.Fatalf(...)
        }
    })
}
```

Or maybe use the same way we used in ramen/e2e - group eqaul and not equal tests and use a function to modify the original step.

File: pkg/test/report_test.go [hunk 25]
```diff
@@ -651,6 +652,300 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+
+	// Canceled status should override even Failed status
+	if r.Status != Canceled {
+		t.Errorf("expected status to be changed to %s, got %s", Canceled, r.Status)
+	}
+}
+
+func TestReportAddSkippedStep(t *testing.T) {
+	skippedStep := &Step{Name: "skipped-step", Status: Skipped, Duration: 0.0}
+	t.Run("Empty status", func(t *testing.T) {
```
Comment (nirs) [inline pkg/test/report_test.go:125]: lower case sub test name

File: pkg/test/report_test.go [hunk 26]
```diff
@@ -651,6 +652,300 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		r.Summary = Summary{Passed: 2}
+		return r
+	}
+
+	// Base report for comparisons
+	baseReport := createReport()
+
+	// intentionally comparing report to itself
+	//nolint:gocritic
+	t.Run("Self equal", func(t *testing.T) {
```
Comment (nirs) [inline pkg/test/report_test.go:244]: lower case sub test names.

File: pkg/test/report_test.go [hunk 27]
```diff
@@ -651,6 +652,300 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		r.Steps = []*Step{
+			{Name: "step1", Status: Passed, Duration: 1.0},
+			{Name: "step2", Status: Passed, Duration: 1.0},
+		}
+		r.Summary = Summary{Passed: 2}
+		return r
+	}
+
+	// Base report for comparisons
+	baseReport := createReport()
```
Comment (nirs) [inline pkg/test/report_test.go:240]: Should we call this "a" and the report we compared to "b"? Or "r1" and "r2"? We use "baseReport" and "r" which is not consistent or clear. baseReport is not a base of the second report, it is just an identical report created by createReport.

File: pkg/test/report_test.go [hunk 28]
```diff
@@ -651,6 +652,300 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		}
+		if baseReport.Equal(r) {
+			t.Error("reports with different step content should not be equal")
+		}
+	})
+}
+
+func TestReportMarshaling(t *testing.T) {
+	fakeTime(t)
+	r1 := newReport("test-command", config)
```
Comment (nirs) [inline pkg/test/report_test.go:344]: We have single report here, so why call it r1?

**Review by nirs — COMMENTED** [review]
Nice!

I think report equal tests with sub tests is better than the table tests for steps.

File: pkg/test/report_test.go (hunk 17 above)
Comment (parikshithb) [reply pkg/test/report_test.go]: Added step and report tests for this. Needs fix #156.

File: pkg/test/report_test.go (hunk 19 above)
Comment (parikshithb) [reply pkg/test/report_test.go]: yeah, we actually do. removed this test.

File: pkg/test/report_test.go (hunk 20 above)
Comment (parikshithb) [reply pkg/test/report_test.go]: Removed multiple lines wherever possible with this update.

File: pkg/test/report_test.go [hunk 29]
```diff
@@ -651,6 +651,399 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		}
+	})
+
+	t.Run("different name", func(t *testing.T) {
+		differentStepName := &Step{
+			Name:     "test",
+			Status:   baseStep.Status,
+			Duration: baseStep.Duration,
+			Config:   baseStep.Config,
+		}
```
Comment (nirs) [inline pkg/test/report_test.go:620]: This basically copy baseStep with one modification. We can do this in a more clear way like this:

```go
differentName := *baseStep
differentName.Name = "test"
```

To make the code more uniform we can create baseStep on the stack:

```go
a := Step{...}
...
t.Run("different name", func(t *testing.T) {
    b := a
    b.Name = "other" 
    if a.Equal(b) {
        t.Fatalf(...)
    }
})
```

This is similar to the way we tested in ramen/e2e/types/config_test.go using a function creating a new config.

Same for all tests bellow changing one field.

File: pkg/test/report_test.go [hunk 30]
```diff
@@ -651,6 +651,399 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		stepB := &Step{
+			Name:     "parent",
+			Status:   Passed,
+			Duration: 1.0,
+			Items: []*Step{
+				{Name: "child1", Status: Passed},
+				{Name: "child2", Status: Failed},
+			},
+		}
```
Comment (nirs) [inline pkg/test/report_test.go:700]: Same here - we can copy stepA an modify:

```go
a := Step{...}
b := a
```

File: pkg/test/report_test.go [hunk 31]
```diff
@@ -651,6 +651,399 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+		stepB := &Step{
+			Name:     "parent",
+			Status:   Passed,
+			Duration: 1.0,
+			Items: []*Step{
+				{Name: "child1", Status: Passed},
+				{Name: "different", Status: Failed},
+			},
+		}
```
Comment (nirs) [inline pkg/test/report_test.go:724]: Here we cannot copy step a and modify, since the copy is shallow. But we can copy and set different steps:

```go
a := Step{...}
b := b
b.Steps = []*Step{
    ...
}

File: pkg/test/report_test.go [hunk 32]
```diff
@@ -651,6 +651,399 @@ func TestReportCleanAllPassed(t *testing.T) {
...
+				nil,
+			},
+		}
+		stepB := &Step{
+			Name:     "parent",
+			Status:   Passed,
+			Duration: 1.0,
+			Items: []*Step{
+				{Name: "child1", Status: Passed},
+				nil,
```
Comment (nirs) [inline pkg/test/report_test.go:769]: nil step should not be possible. We should panic if you try to add a nil step.

**Comment by nirs** [comment]
@parikshithb I rebased to see if this tests pass now.

**Review by nirs — APPROVED** [review]
Thanks!
