### PR TITLE
Fix ramen controller type validation for upstream ramen

### LINKED ISSUE #419: ramen controller type empty with ramen main
Running validate clusters with ramen main fails.

## Example run

```console
% ramenctl validate clusters -o out/ramen-deployed-and-configured-fix
⭐ Using config "config.yaml"
⭐ Using report "out/ramen-deployed-and-configured-fix"

🔎 Validate config ...
   ✅ Config validated

🔎 Validate clusters ...
   ✅ Gathered data from cluster "hub"
   ✅ Gathered data from cluster "dr2"
   ✅ Gathered data from cluster "dr1"
   ✅ Inspected S3 profiles
   ✅ Checked S3 profile "minio-on-dr1"
   ✅ Checked S3 profile "minio-on-dr2"
   ❌ Issues found during validation

❌ validation failed (87 ok, 0 stale, 3 problem)
```

### clustersStatus

```yaml
clustersStatus:
  clusters:
  - name: dr1
    ramen:
      configmap:
        deleted:
          state: ok ✅
        name: ramen-dr-cluster-operator-config
        namespace: ramen-system
        ramenControllerType:
          description: Expecting controller type "dr-cluster"
          state: problem ❌
  ...
  - name: dr2
    ramen:
      configmap:
        deleted:
          state: ok ✅
        name: ramen-dr-cluster-operator-config
        namespace: ramen-system
        ramenControllerType:
          description: Expecting controller type "dr-cluster"
          state: problem ❌
  ...
  hub:
  ...
    ramen:
      configmap:
        deleted:
          state: ok ✅
        name: ramen-hub-operator-config
        namespace: ramen-system
        ramenControllerType:
          description: Expecting controller type "dr-hub"
          state: problem ❌
```

## How to get controller type in new ramen

The controller type is set now using manager container environment variable:

### validate-clusters.data/hub/namespaces/ramen-system/apps/deployments/ramen-hub-operator.yaml

```yaml
spec:
  ...
  template:
    ...
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: RAMEN_CONTROLLER_TYPE
          value: dr-hub
...
```

### validate-clusters.data/dr1/namespaces/ramen-system/apps/deployments/ramen-dr-cluster-operator.yaml

```yaml
spec:
  ...
  template:
    ...
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: RAMEN_CONTROLLER_TYPE
          value: dr-cluster
...
```

## Fix

- Lookup RAMEN_CONTROLLER_TYPE in container[0].env
- If not found we have older ramen, fallback to configmap
- Move the value to the ramen deployment as virtual key. We don't want to show the env values
- Update the html template (remove key from configmap, add to deployment)

Suggested new yaml

```yaml
      deployment:
        conditions:
        - state: ok ✅
          type: Available
        - state: ok ✅
          type: Progressing
        deleted:
          state: ok ✅
        name: ramen-dr-cluster-operator
        namespace: ramen-system
        ramenControllerType:
          state: ok ✅
          value: dr-hub
        replicas:
          state: ok ✅
          value: 1
```

### PR DESCRIPTION
**Pull request by nirs**
Since ODF 4.22, ramen sets the controller type via the
`RAMEN_CONTROLLER_TYPE` environment variable in the deployment's
manager container instead of the configmap's `ramen_manager_config.yaml`.

### Behavior changes

- Support the modern controller type location (deployment env var),
  used since ODF 4.22.
- Fall back to the legacy location (configmap) to support older ramen
  versions.
- Report a problem when the controller type cannot be determined from
  either source. Previously this was silently skipped.

### Preparing the code

The existing code mixed reading resources with validation, making it
hard to pass resources to new validation functions. The first commits
refactor the code to separate concerns:

1. Extract `readRamenDeployment()` and `readRamenConfigMap()` helpers.
2. Move reads into `validateRamen`, so validation functions receive
   objects directly (or nil for missing resources).
3. Extract `ParseRamenConfig()` into the ramen package for reuse.
4. Move the `RamenControllerType` field from `ConfigMapSummary` to
   `DeploymentSummary` in the report, reflecting the new location.
5. Add `validateControllerType` with deployment-first, configmap-fallback
   logic and `DeploymentControllerType()` helper in the ramen package.

## Example run

```console
% ramenctl validate clusters -o out
⭐ Using config "config.yaml"
⭐ Using report "out"

🔎 Validate config ...
   ✅ Config validated

🔎 Validate clusters ...
   ✅ Gathered data from cluster "hub"
   ✅ Gathered data from cluster "dr1"
   ✅ Gathered data from cluster "dr2"
   ✅ Inspected S3 profiles
   ✅ Checked S3 profile "minio-on-dr1"
   ✅ Checked S3 profile "minio-on-dr2"
   ✅ Clusters validated

✅ Validation completed (90 ok, 0 stale, 0 problem)
```

## Example HTML report

Screenshot 2026-04-15 at 21 53 31

## Example YAML report

```console
clustersStatus:
  clusters:
    - name: dr1
      ramen:
        configmap:
          deleted:
            state: ok ✅
          name: ramen-dr-cluster-operator-config
          namespace: ramen-system
          s3StoreProfiles:
            state: ok ✅
            value:
              - bucket:
                  state: ok ✅
                  value: bucket
                caCertificate:
                  state: ok ✅
                endpoint:
                  state: ok ✅
                  value: http://192.168.105.16:30000
                profileName: minio-on-dr1
                region:
                  state: ok ✅
                  value: us-west-1
                secret:
                  awsAccessKeyID:
                    state: ok ✅
                    value: AF:11:8B:2D:C7:90:42:90:A4:2F:22:8F:AE:81:37:00:9B:6D:2A:19:6E:42:3E:FA:4A:06:0E:D0:6F:A2:7E:9D
                  awsSecretAccessKey:
                    state: ok ✅
                    value: AA:C9:36:7D:4A:F6:BA:48:21:EF:5D:89:81:BE:4D:71:21:7A:0D:67:09:9D:2A:97:8A:31:03:3F:6A:3B:AE:89
                  deleted:
                    state: ok ✅
                  name:
                    state: ok ✅
                    value: ramen-s3-secret-dr1
                  namespace:
                    state: ok ✅
                    value: ramen-system
              - bucket:
                  state: ok ✅
                  value: bucket
                caCertificate:
                  state: ok ✅
                endpoint:
                  state: ok ✅
                  value: http://192.168.105.17:30000
                profileName: minio-on-dr2
                region:
                  state: ok ✅
                  value: us-east-1
                secret:
                  awsAccessKeyID:
                    state: ok ✅
                    value: AF:11:8B:2D:C7:90:42:90:A4:2F:22:8F:AE:81:37:00:9B:6D:2A:19:6E:42:3E:FA:4A:06:0E:D0:6F:A2:7E:9D
                  awsSecretAccessKey:
                    state: ok ✅
                    value: AA:C9:36:7D:4A:F6:BA:48:21:EF:5D:89:81:BE:4D:71:21:7A:0D:67:09:9D:2A:97:8A:31:03:3F:6A:3B:AE:89
                  deleted:
                    state: ok ✅
                  name:
                    state: ok ✅
                    value: ramen-s3-secret-dr2
                  namespace:
                    state: ok ✅
                    value: ramen-system
        deployment:
          conditions:
            - state: ok ✅
              type: Available
            - state: ok ✅
              type: Progressing
          deleted:
            state: ok ✅
          name: ramen-dr-cluster-operator
          namespace: ramen-system
          ramenControllerType:
            state: ok ✅
            value: dr-cluster
          replicas:
            state: ok ✅
            value: 1
    - name: dr2
      ramen:
        configmap:
          deleted:
            state: ok ✅
          name: ramen-dr-cluster-operator-config
          namespace: ramen-system
          s3StoreProfiles:
            state: ok ✅
            value:
              - bucket:
                  state: ok ✅
                  value: bucket
                caCertificate:
                  state: ok ✅
                endpoint:
                  state: ok ✅
                  value: http://192.168.105.16:30000
                profileName: minio-on-dr1
                region:
                  state: ok ✅
                  value: us-west-1
                secret:
                  awsAccessKeyID:
                    state: ok ✅
                    value: AF:11:8B:2D:C7:90:42:90:A4:2F:22:8F:AE:81:37:00:9B:6D:2A:19:6E:42:3E:FA:4A:06:0E:D0:6F:A2:7E:9D
                  awsSecretAccessKey:
                    state: ok ✅
                    value: AA:C9:36:7D:4A:F6:BA:48:21:EF:5D:89:81:BE:4D:71:21:7A:0D:67:09:9D:2A:97:8A:31:03:3F:6A:3B:AE:89
                  deleted:
                    state: ok ✅
                  name:
                    state: ok ✅
                    value: ramen-s3-secret-dr1
                  namespace:
                    state: ok ✅
                    value: ramen-system
              - bucket:
                  state: ok ✅
                  value: bucket
                caCertificate:
                  state: ok ✅
                endpoint:
                  state: ok ✅
                  value: http://192.168.105.17:30000
                profileName: minio-on-dr2
                region:
                  state: ok ✅
                  value: us-east-1
                secret:
                  awsAccessKeyID:
                    state: ok ✅
                    value: AF:11:8B:2D:C7:90:42:90:A4:2F:22:8F:AE:81:37:00:9B:6D:2A:19:6E:42:3E:FA:4A:06:0E:D0:6F:A2:7E:9D
                  awsSecretAccessKey:
                    state: ok ✅
                    value: AA:C9:36:7D:4A:F6:BA:48:21:EF:5D:89:81:BE:4D:71:21:7A:0D:67:09:9D:2A:97:8A:31:03:3F:6A:3B:AE:89
                  deleted:
                    state: ok ✅
                  name:
                    state: ok ✅
                    value: ramen-s3-secret-dr2
                  namespace:
                    state: ok ✅
                    value: ramen-system
        deployment:
          conditions:
            - state: ok ✅
              type: Available
            - state: ok ✅
              type: Progressing
          deleted:
            state: ok ✅
          name: ramen-dr-cluster-operator
          namespace: ramen-system
          ramenControllerType:
            state: ok ✅
            value: dr-cluster
          replicas:
            state: ok ✅
            value: 1
  hub:
    drClusters:
      state: ok ✅
      value:
        - conditions:
            - state: ok ✅
              type: Validated
            - state: ok ✅
              type: Fenced
            - state: ok ✅
              type: Clean
          name: dr1
          phase: Available
        - conditions:
            - state: ok ✅
              type: Validated
            - state: ok ✅
              type: Fenced
            - state: ok ✅
              type: Clean
          name: dr2
          phase: Available
    drPolicies:
      state: ok ✅
      value:
        - conditions:
            - state: ok ✅
              type: Validated
          drClusters:
            - dr1
            - dr2
          name: dr-policy-1m
          peerClasses:
            state: ok ✅
            value:
              - replicationID: rook-ceph-replication-1
                storageClassName: rook-ceph-block
              - storageClassName: rook-cephfs-fs1
          schedulingInterval: 1m
        - conditions:
            - state: ok ✅
              type: Validated
          drClusters:
            - dr1
            - dr2
          name: dr-policy-5m
          peerClasses:
            state: ok ✅
            value:
              - replicationID: rook-ceph-replication-1
                storageClassName: rook-ceph-block
              - storageClassName: rook-cephfs-fs1
          schedulingInterval: 5m
    ramen:
      configmap:
        deleted:
          state: ok ✅
        name: ramen-hub-operator-config
        namespace: ramen-system
        s3StoreProfiles:
          state: ok ✅
          value:
            - bucket:
                state: ok ✅
                value: bucket
              caCertificate:
                state: ok ✅
              endpoint:
                state: ok ✅
                value: http://192.168.105.16:30000
              profileName: minio-on-dr1
              region:
                state: ok ✅
                value: us-west-1
              secret:
                awsAccessKeyID:
                  state: ok ✅
                  value: AF:11:8B:2D:C7:90:42:90:A4:2F:22:8F:AE:81:37:00:9B:6D:2A:19:6E:42:3E:FA:4A:06:0E:D0:6F:A2:7E:9D
                awsSecretAccessKey:
                  state: ok ✅
                  value: AA:C9:36:7D:4A:F6:BA:48:21:EF:5D:89:81:BE:4D:71:21:7A:0D:67:09:9D:2A:97:8A:31:03:3F:6A:3B:AE:89
                deleted:
                  state: ok ✅
                name:
                  state: ok ✅
                  value: ramen-s3-secret-dr1
                namespace:
                  state: ok ✅
                  value: ramen-system
            - bucket:
                state: ok ✅
                value: bucket
              caCertificate:
                state: ok ✅
              endpoint:
                state: ok ✅
                value: http://192.168.105.17:30000
              profileName: minio-on-dr2
              region:
                state: ok ✅
                value: us-east-1
              secret:
                awsAccessKeyID:
                  state: ok ✅
                  value: AF:11:8B:2D:C7:90:42:90:A4:2F:22:8F:AE:81:37:00:9B:6D:2A:19:6E:42:3E:FA:4A:06:0E:D0:6F:A2:7E:9D
                awsSecretAccessKey:
                  state: ok ✅
                  value: AA:C9:36:7D:4A:F6:BA:48:21:EF:5D:89:81:BE:4D:71:21:7A:0D:67:09:9D:2A:97:8A:31:03:3F:6A:3B:AE:89
                deleted:
                  state: ok ✅
                name:
                  state: ok ✅
                  value: ramen-s3-secret-dr2
                namespace:
                  state: ok ✅
                  value: ramen-system
      deployment:
        conditions:
          - state: ok ✅
            type: Available
          - state: ok ✅
            type: Progressing
        deleted:
          state: ok ✅
        name: ramen-hub-operator
        namespace: ramen-system
        ramenControllerType:
          state: ok ✅
          value: dr-hub
        replicas:
          state: ok ✅
          value: 1
  s3:
    profiles:
      state: ok ✅
      value:
        - accessible:
            state: ok ✅
            value: true
          name: minio-on-dr1
        - accessible:
            state: ok ✅
            value: true
          name: minio-on-dr2
```

---
Fixes: #419

### CODE REVIEW

File: pkg/ramen/ramen.go [hunk 1]
```diff
@@ -58,6 +59,16 @@ const (
 	// OperatorReplicas is the number of pods in the ramen operator deployment.
 	// TODO: discover the value from the cluster.
 	OperatorReplicas = 1
+
+	// ControllerTypeEnvName is the environment variable name for the controller type
+	// in the ramen operator deployment manager container. Used since ODF 4.22.
+	// In older versions, the controller type is set in the ramen configmap.
+	// TODO: consume this constant from the ramen API when it is exported.
+	ControllerTypeEnvName = "RAMEN_CONTROLLER_TYPE"
```
Comment (nirs) [inline pkg/ramen/ramen.go:67]: Added https://github.com/RamenDR/ramen/issues/2515

File: pkg/ramen/ramen.go [hunk 2]
```diff
@@ -58,6 +59,16 @@ const (
...
+
+	// ManagerContainerName is the name of the manager container in the ramen operator deployment.
+	// TODO: consume this constant from the ramen API when it is exported.
+	ManagerContainerName = "manager"
```
Comment (nirs) [inline pkg/ramen/ramen.go:71]: Same issue https://github.com/RamenDR/ramen/issues/2515

**Comment by nirs** [comment]
Latest version adds link to the ramen issue for adding constants.

**Review by parikshithb — APPROVED** [review]
looks great!
