### PR TITLE
s3: Report error when object downloads fail

### LINKED ISSUE #425: ramenctl validate application fails to report noobaa bucket download test failed
Version v0.19.0 ramenctl "validate application" fails to report one managed cluster noobaa bucket download test failed in ODF 4.21 RDR test environment.

```
% tree ~/Downloads/out-busybox-ceph-as/validate-application.data/s3
/Users/nir/Downloads/out-busybox-ceph-as/validate-application.data/s3
├── s3profile-hyper3-ocs-storagecluster
└── s3profile-hyper4-ocs-storagecluster
    └── busybox-cephfs-as
        └── busybox-cephfs-as-placement-drpc
            └── v1alpha1.VolumeReplicationGroup
                └── a
```

[out-busybox-ceph-as.tar.gz](https://github.com/user-attachments/files/26906233/out-busybox-ceph-as.tar.gz)

### PR DESCRIPTION
**Pull request by parikshithb**
When downloading objects from S3, individual download failures were logged as warnings but not returned as errors. This caused callers like validate-application to mark S3 profiles as "gathered: ok" when objects were listed and couldnt actually be downloaded.

Collect per-object download errors and return them when any downloads fail.

Fixes #425

### CODE REVIEW

**Comment by nirs** [comment]
> When downloading objects from S3, individual download failures were logged as warnings but not returned as errors. This caused callers like validate-application to mark S3 profiles as "gathered: ok" when objects were listed and couldnt actually be downloaded.
> 
> Collect per-object download errors and return them when any downloads fail.

Returning an error makes sense, but it should not include all errors. For example if we had 10 errors (or 1000 with big discovered app) we cannot show all errors in the yaml or html report. When we fail the operation, we need to show one error describing all the errors (that should be logged as we do today). Something like:

    failed to download 3 objects of 11

The error should be short and clean so it looks good in the reports. For full info, the developer inspecting the report can look at the log.

But failing the operation is not enough - the s3 profile should snow:

```yaml
s3:
- name: profile-name
  gathered:
    value: false
    state: problem
    description: failed to download 3 objects of 11 
```

Maybe we can show the object count instead of true/false?

Please share example run console output and o output directory so we can evaluate this fix.

File: pkg/s3/s3.go [hunk 1]
```diff
@@ -250,14 +250,21 @@ func (s *objectStore) downloadObjects(ctx context.Context, prefix, outputDir str
 			profileDir, prefix, err)
 	}
 
-	downloaded := 0
+	var errs []error
```
Comment (nirs) [inline pkg/s3/s3.go]: Let's count number of failed downloads - makes it easier to create the error later.

File: pkg/s3/s3.go
Comment (nirs) [inline pkg/s3/s3.go]: We should fail - a healthy application must have some object in s3.

Instead of warning return an error:

```go
return fmt.Errorf("no objects found in bucket %q for prefix %q", s.profile.Bucket, prefix)
```

File: pkg/s3/s3.go [hunk 2]
```diff
@@ -250,14 +250,21 @@ func (s *objectStore) downloadObjects(ctx context.Context, prefix, outputDir str
...
 		}
-		downloaded++
+	}
+
+	downloaded := len(keys) - len(errs)
+
+	if len(errs) > 0 {
+		return fmt.Errorf("downloaded %d/%d objects from bucket %q: %w",
+			downloaded, len(keys), s.profile.Bucket, errors.Join(errs...))
 	}
```
Comment (nirs) [inline pkg/s3/s3.go:267]: This should provide an error which is more useful for the reports.

```go
if failed > 0 {
   return fmt.Errorf("failed to download %d of %d objects from bucket %q",
			failed, len(keys), s.profile.Bucket) 
}
```

In the related bug we would see:

    failed to download 1 of 1 objects from ...

**Comment by parikshithb** [comment]
Addressed comments.

Tested by scaling down minio on dr1. (No objects found to download):
(could not simulate list obj pass but download fail)

validate application:
```
./ramenctl validate application --namespace argocd --name appset-deploy-rbd --output out/v_app_fail
⭐ Using config "config.yaml"
⭐ Using report "out/v_app_fail"

🔎 Validate config ...
   ✅ Config validated

🔎 Validate application ...
   ✅ Inspected application

   ✅ Gathered data from cluster "hub"
   ✅ Gathered data from cluster "dr2"
   ✅ Gathered data from cluster "dr1"
   ✅ Inspected S3 profiles
   ✅ Gathered S3 profile "minio-on-dr2"
   ❌ Failed to gather S3 profile "minio-on-dr1"
   ❌ Issues found during validation

❌ validation failed (23 ok, 0 stale, 1 problem)
```
report:
```
  s3:
    profiles:
      state: ok ✅
      value:
      - gathered:
          state: ok ✅
          value: true
        name: minio-on-dr2
      - gathered:
          description: 'failed to download objects from profile "minio-on-dr1": failed
            to list objects in bucket "bucket" with prefix "test-appset-deploy-rbd/appset-deploy-rbd/":
            operation error S3: ListObjectsV2, exceeded maximum number of attempts,
            3, https response error StatusCode: 0, RequestID: , HostID: , request
            send failed, Get "http://192.168.105.4:30000/bucket?list-type=2&prefix=test-appset-deploy-rbd%2Fappset-deploy-rbd%2F":
            dial tcp 192.168.105.4:30000: connect: connection refused'
          state: problem ❌
        name: minio-on-dr1
  secondaryCluster:
    name: dr2
    vrg:
      conditions:
      - state: ok ✅
        type: NoClusterDataConflict
      deleted:
        state: ok ✅
      name: appset-deploy-rbd
      namespace: test-appset-deploy-rbd
      state:
        state: ok ✅
        value: Secondary
```
html:

Screenshot 2026-04-27 at 7 23 30 PM




Change is not applicable for `validate clusters` command since we use `HeadBucket`.

File: pkg/s3/s3.go [hunk 3]
```diff
@@ -250,14 +249,21 @@ func (s *objectStore) downloadObjects(ctx context.Context, prefix, outputDir str
...
 		if err := s.downloadObject(ctx, key, profileDir); err != nil {
 			s.log.Warnf("Failed to download object %q from bucket %q: %v",
 				key, s.profile.Bucket, err)
+			failed++
 			continue
 		}
-		downloaded++
+	}
+
+	downloaded := len(keys) - failed
```
Comment (nirs) [inline pkg/s3/s3.go]: This is not needed now - since we fail here.

File: pkg/s3/s3.go
Comment (nirs) [inline pkg/s3/s3.go]: Now the line is logged only if we download all objects, so we can update the text so:

    Downloaded %d objects ...

**Comment by nirs** [comment]
> Addressed comments.
> 
> Tested by scaling down minio on dr1. (No objects found to download): (could not simulate list obj pass but download fail)

We can change the code to fail some objects by name for testing the behavior.
I think we already have a test for this, so we can use the test to check the output.

> report:
> 
> ```
>   s3:
>     profiles:
>       state: ok ✅
>       value:
>       - gathered:
>           state: ok ✅
>           value: true
>         name: minio-on-dr2
>       - gathered:
>           description: 'failed to download objects from profile "minio-on-dr1": failed
>             to list objects in bucket "bucket" with prefix "test-appset-deploy-rbd/appset-deploy-rbd/":
>             operation error S3: ListObjectsV2, exceeded maximum number of attempts,
>             3, https response error StatusCode: 0, RequestID: , HostID: , request
>             send failed, Get "http://192.168.105.4:30000/bucket?list-type=2&prefix=test-appset-deploy-rbd%2Fappset-deploy-rbd%2F":
>             dial tcp 192.168.105.4:30000: connect: connection refused'

This error is too verbose - it is great for the log. For the report it is better to have a shorter high level message like we have in other cases.

**Comment by parikshithb** [comment]
Addressed review comments. Short error messages from download, list and check(headbucket) are now returned for reports.

validate application:

```
./ramenctl validate application --namespace argocd --name appset-deploy-rbd --output out/v_app_fail_3
⭐ Using config "config.yaml"
⭐ Using report "out/v_app_fail_3"

🔎 Validate config ...
   ✅ Config validated

🔎 Validate application ...
   ✅ Inspected application
   ✅ Gathered data from cluster "hub"
   ✅ Gathered data from cluster "dr2"
   ✅ Gathered data from cluster "dr1"
   ✅ Inspected S3 profiles
   ✅ Gathered S3 profile "minio-on-dr2"
   ❌ Failed to gather S3 profile "minio-on-dr1"
   ❌ Issues found during validation

❌ validation failed (21 ok, 0 stale, 3 problem)
```

report:
```
  s3:
    profiles:
      state: ok ✅
      value:
      - gathered:
          state: ok ✅
          value: true
        name: minio-on-dr2
      - gathered:
          description: 'failed to download objects from profile "minio-on-dr1": failed
            to list objects in bucket "bucket" with prefix "test-appset-deploy-rbd/appset-deploy-rbd/"'
          state: problem ❌
        name: minio-on-dr1
  secondaryCluster:
    name: dr2
    vrg:
      conditions:
      - state: ok ✅
        type: NoClusterDataConflict
      deleted:
        state: ok ✅
      name: appset-deploy-rbd
      namespace: test-appset-deploy-rbd
      state:
        state: ok ✅
        value: Secondary
```
html:
Screenshot 2026-04-28 at 7 53 56 PM


validate clusters:

```
./ramenctl validate clusters --output out/v_clu_fail
⭐ Using config "config.yaml"
⭐ Using report "out/v_clu_fail"

🔎 Validate config ...
   ✅ Config validated

🔎 Validate clusters ...
   ✅ Gathered data from cluster "hub"
   ✅ Gathered data from cluster "dr2"
   ✅ Gathered data from cluster "dr1"
   ✅ Inspected S3 profiles
   ✅ Checked S3 profile "minio-on-dr2"
   ❌ Failed to check S3 profile "minio-on-dr1"
   ❌ Issues found during validation

❌ validation failed (89 ok, 0 stale, 1 problem)
```

report:
```
 s3:
    profiles:
      state: ok ✅
      value:
      - gathered:
          state: ok ✅
          value: true
        name: minio-on-dr2
      - gathered:
          description: 'failed to download objects from profile "minio-on-dr1": failed
            to list objects in bucket "bucket" with prefix "test-appset-deploy-rbd/appset-deploy-rbd/"'
          state: problem ❌
        name: minio-on-dr1
  secondaryCluster:
    name: dr2
    vrg:
      conditions:
      - state: ok ✅
        type: NoClusterDataConflict
      deleted:
        state: ok ✅
      name: appset-deploy-rbd
      namespace: test-appset-deploy-rbd
      state:
        state: ok ✅
        value: Secondary
```

html:
Screenshot 2026-04-28 at 7 54 58 PM

**Review by nirs — APPROVED** [review]
Thanks!
