### PR TITLE
test: Run all tests in parallel

### LINKED ISSUE #39: Run all tests in parallel
We want to tun all configured tests in parallel.

- Change console.Progress to log complete line. We cannot use \r when running tests in parallel
  - We can add a fancy progress later that can show parallel execution
- Start each test in goroutine
- Wait until all tests complete
- Simple test summary (6 passed, 0 failed)

Implementation notes:

- keep test status in Test.error
- create list of tests
- run tests in parallel
  - no limit for now, can improve later
- wait for completion
- report test summary
- fail if some tests failed

### LINKED ISSUE #54: Test nested progress
Show how steps are nested, add whitespace to break long output to smaller sections.

## Example run

```console
% ramenctl test run -o test
⭐ Using report "test"
⭐ Using config "config.yaml"

🔎 Setup environment ...
   ✅ Environment setup

🔎 Testing applications ...
   ✅ Application "appset-deploy-cephfs" deployed
   ✅ Application "appset-deploy-rbd" deployed
   ✅ Application "appset-deploy-rbd" protected
   ✅ Application "appset-deploy-cephfs" protected
   ✅ Application "appset-deploy-cephfs" failed over
   ✅ Application "appset-deploy-rbd" failed over
   ✅ Application "appset-deploy-cephfs" relocated
   ✅ Application "appset-deploy-rbd" relocated
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-cephfs" undeployed
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "appset-deploy-rbd" undeployed

✅ passed (2 passed, 0 failed, 0 skipped)
```

## Example clean

```console
% ramenctl test clean -o test
⭐ Using report "test"
⭐ Using config "config.yaml"

🔎 Clean applications ...
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "appset-deploy-cephfs" undeployed
   ✅ Application "appset-deploy-rbd" undeployed

🔎 Clean environment ...
   ✅ Environment cleaned

✅ passed (2 passed, 0 failed, 0 skipped)
```

## Example screenshot (dark mode)

Image

### PR DESCRIPTION
**Pull request by nirs**
Run all tests in parallel similar to ramen/e2e tests.

Improve the output to more more clear when running multiple tests by separating the output to multiple groups of steps.

## Example run

Using 2 tests, expected usage for ramenctl.

```console
% ramenctl test run -o test
⭐ Using report "test"
⭐ Using config "config.yaml"

🔎 Setup environment ...
   ✅ Environment setup

🔎 Run tests ...
   ✅ Application "appset-deploy-rbd" deployed
   ✅ Application "appset-deploy-cephfs" deployed
   ✅ Application "appset-deploy-cephfs" protected
   ✅ Application "appset-deploy-rbd" protected
   ✅ Application "appset-deploy-cephfs" failed over
   ✅ Application "appset-deploy-rbd" failed over
   ✅ Application "appset-deploy-cephfs" relocated
   ✅ Application "appset-deploy-rbd" relocated
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-cephfs" undeployed
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "appset-deploy-rbd" undeployed

✅ passed (2 passed, 0 failed, 0 skipped)
```

## Example clean

Using 2 tests, expected usage for ramenctl.

```console
% ramenctl test clean -o test
⭐ Using report "test"
⭐ Using config "config.yaml"

🔎 Clean tests ...
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "appset-deploy-rbd" undeployed
   ✅ Application "appset-deploy-cephfs" undeployed

🔎 Clean environment ...
   ✅ Environment cleaned

✅ passed (2 passed, 0 failed, 0 skipped)
```

### Run report

```yaml
host:
  arch: arm64
  cpus: 12
  os: darwin
name: test-run
ramenctl:
  commit: b5e7ffde13922f0fe0695f404026cd27bb33c34b
  version: v0.1.0-19-gb5e7ffd
status: passed
steps:
- name: setup
  status: passed
- name: tests
  status: passed
  tests:
  - deployer: appset
    pvcSpec: cephfs
    status: passed
    workload: deploy
  - deployer: appset
    pvcSpec: rbd
    status: passed
    workload: deploy
summary:
  failed: 0
  passed: 2
  skipped: 0
```

### Clean report

```yaml
% cat test/test-clean.yaml
host:
  arch: arm64
  cpus: 12
  os: darwin
name: test-clean
ramenctl:
  commit: b5e7ffde13922f0fe0695f404026cd27bb33c34b
  version: v0.1.0-19-gb5e7ffd
status: passed
steps:
- name: tests
  status: passed
  tests:
  - deployer: appset
    pvcSpec: rbd
    status: passed
    workload: deploy
  - deployer: appset
    pvcSpec: cephfs
    status: passed
    workload: deploy
- name: cleanup
  status: passed
summary:
  failed: 0
  passed: 2
  skipped: 0
```

### Test tarball

[test.tar.gz](https://github.com/user-attachments/files/19409854/test.tar.gz)

Fixes #39 
Fixes #54

### CODE REVIEW

File: pkg/test/clean.go [hunk 1]
```diff
@@ -3,15 +3,26 @@
...
+	var wg sync.WaitGroup
+	for _, tc := range cmd.Config.Tests {
+		test := newTest(tc, cmd)
+		wg.Add(1)
+		go func() {
+			cmd.CleanTest(test)
+			wg.Done()
+		}()
+	}
+	wg.Wait()
```
Comment (nirs) [inline pkg/test/clean.go:23]: We have the same loop in run and clean. We can keep one loop accepting a test function instead. This will be useful when we want to limit the number of concurrent tests, or adding cancellation.

We also need validation step which must be done before starting the tests, again same for run and clean, so this should be implemented in Command.

File: pkg/test/command.go [hunk 2]
```diff
@@ -110,6 +110,12 @@ func (c *Command) CleanTest(test *Test) bool {
 	return true
 }
 
+func (c *Command) IsFailed() bool {
```
Comment (nirs) [inline pkg/test/command.go:113]: IsFailed() and Failed() are not great names.

Maybe use Context interface:

```
Done() <- chan(struct{})
Fail() error
Pass()
```

Done() can be useful if we want to support cancellation later.

File: pkg/test/run.go [hunk 3]
```diff
@@ -15,9 +17,18 @@ func Run(configFile string, outputDir string) error {
...
+	var wg sync.WaitGroup
+	for _, tc := range cmd.Config.Tests {
+		test := newTest(tc, cmd)
+		wg.Add(1)
+		go func() {
+			cmd.RunTest(test)
+			wg.Done()
+		}()
+	}
+	wg.Wait()
```
Comment (nirs) [inline pkg/test/run.go:29]: Can be nicer as cmd.RunTests()

**Comment by nirs** [comment]
## Example failed run

The disapp cephfs application failed (known issue).

### test run

```console
% ramenctl test run -o test
⭐ Using report "test"
⭐ Using config "config.yaml"

🔎 Setup environment ...
   ✅ Environment setup

🔎 Run tests ...
   ✅ Application "appset-deploy-cephfs" deployed
   ✅ Application "appset-deploy-rbd" deployed
   ✅ Application "disapp-deploy-cephfs" deployed
   ✅ Application "disapp-deploy-rbd" deployed
   ✅ Application "subscr-deploy-cephfs" deployed
   ✅ Application "subscr-deploy-rbd" deployed
   ✅ Application "appset-deploy-cephfs" protected
   ✅ Application "appset-deploy-rbd" protected
   ✅ Application "disapp-deploy-rbd" protected
   ✅ Application "subscr-deploy-rbd" protected
   ✅ Application "disapp-deploy-cephfs" protected
   ✅ Application "subscr-deploy-cephfs" protected
   ✅ Application "appset-deploy-cephfs" failed over
   ✅ Application "disapp-deploy-cephfs" failed over
   ✅ Application "subscr-deploy-cephfs" failed over
   ✅ Application "disapp-deploy-rbd" failed over
   ✅ Application "appset-deploy-rbd" failed over
   ✅ Application "subscr-deploy-rbd" failed over
   ✅ Application "disapp-deploy-rbd" relocated
   ✅ Application "disapp-deploy-rbd" unprotected
   ✅ Application "subscr-deploy-rbd" relocated
   ✅ Application "disapp-deploy-rbd" undeployed
   ✅ Application "appset-deploy-rbd" relocated
   ✅ Application "subscr-deploy-cephfs" relocated
   ✅ Application "subscr-deploy-rbd" unprotected
   ✅ Application "subscr-deploy-rbd" undeployed
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "appset-deploy-rbd" undeployed
   ✅ Application "subscr-deploy-cephfs" unprotected
   ✅ Application "subscr-deploy-cephfs" undeployed
   ✅ Application "appset-deploy-cephfs" relocated
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-cephfs" undeployed
   ❌ failed to relocate application "disapp-deploy-cephfs": workload "deploy-cephfs" is not ready yet before timeout of 10m0s in cluster "dr1"

❌ failed (5 passed, 1 failed, 0 skipped)
```

### test clean

```console
)% ramenctl test clean -o test
⭐ Using report "test"
⭐ Using config "config.yaml"

🔎 Clean tests ...
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "subscr-deploy-rbd" unprotected
   ✅ Application "disapp-deploy-rbd" unprotected
   ✅ Application "subscr-deploy-cephfs" unprotected
   ✅ Application "subscr-deploy-rbd" undeployed
   ✅ Application "appset-deploy-cephfs" undeployed
   ✅ Application "appset-deploy-rbd" undeployed
   ✅ Application "subscr-deploy-cephfs" undeployed
   ✅ Application "disapp-deploy-rbd" undeployed
   ✅ Application "disapp-deploy-cephfs" unprotected
   ✅ Application "disapp-deploy-cephfs" undeployed

🔎 Clean environment ...
   ✅ Environment cleaned

✅ passed (6 passed, 0 failed, 0 skipped)
```

### Test report

**Comment by nirs** [comment]
## Test hub failure

I started test and stop the hub cluster when all tests started failover.

### test run

```console
% ramenctl test run -o test
⭐ Using report "test"
⭐ Using config "config.yaml"

🔎 Setup environment ...
   ✅ Environment setup

🔎 Run tests ...
   ✅ Application "appset-deploy-rbd" deployed
   ✅ Application "appset-deploy-cephfs" deployed
   ✅ Application "disapp-deploy-cephfs" deployed
   ✅ Application "disapp-deploy-rbd" deployed
   ✅ Application "subscr-deploy-cephfs" deployed
   ✅ Application "subscr-deploy-rbd" deployed
   ✅ Application "appset-deploy-rbd" protected
   ✅ Application "disapp-deploy-rbd" protected
   ✅ Application "subscr-deploy-cephfs" protected
   ✅ Application "subscr-deploy-rbd" protected
   ✅ Application "appset-deploy-cephfs" protected
   ✅ Application "disapp-deploy-cephfs" protected
   ❌ failed to failover application "appset-deploy-rbd": Get "https://192.168.105.33:6443/apis/ramendr.openshift.io/v1alpha1/namespaces/argocd/drplacementcontrols/appset-deploy-rbd": dial tcp 192.168.105.33:6443: connect: operation timed out
   ❌ failed to failover application "appset-deploy-cephfs": Get "https://192.168.105.33:6443/apis/ramendr.openshift.io/v1alpha1/namespaces/argocd/drplacementcontrols/appset-deploy-cephfs": dial tcp 192.168.105.33:6443: connect: operation timed out
   ❌ failed to failover application "subscr-deploy-cephfs": Get "https://192.168.105.33:6443/apis/ramendr.openshift.io/v1alpha1/namespaces/test-subscr-deploy-cephfs/drplacementcontrols/subscr-deploy-cephfs": dial tcp 192.168.105.33:6443: connect: operation timed out
   ❌ failed to failover application "subscr-deploy-rbd": Get "https://192.168.105.33:6443/apis/ramendr.openshift.io/v1alpha1/namespaces/test-subscr-deploy-rbd/drplacementcontrols/subscr-deploy-rbd": dial tcp 192.168.105.33:6443: connect: operation timed out
   ❌ failed to failover application "disapp-deploy-cephfs": Get "https://192.168.105.33:6443/apis/ramendr.openshift.io/v1alpha1/namespaces/ramen-ops/drplacementcontrols/disapp-deploy-cephfs": dial tcp 192.168.105.33:6443: connect: operation timed out
   ❌ failed to failover application "disapp-deploy-rbd": Get "https://192.168.105.33:6443/apis/ramendr.openshift.io/v1alpha1/namespaces/ramen-ops/drplacementcontrols/disapp-deploy-rbd": dial tcp 192.168.105.33:6443: i/o timeout

❌ failed (0 passed, 6 failed, 0 skipped)
```

### test clean

```console
% ramenctl test clean -o test
⭐ Using report "test"
⭐ Using config "config.yaml"

🔎 Clean tests ...
I0323 18:28:16.850222   75967 request.go:700] Waited for 1.179533417s due to client-side throttling, not priority and fairness, request: GET:https://192.168.105.33:6443/apis/ramendr.openshift.io/v1alpha1/namespaces/test-subscr-deploy-cephfs/drplacementcontrols/subscr-deploy-cephfs
   ✅ Application "disapp-deploy-cephfs" unprotected
   ✅ Application "subscr-deploy-rbd" unprotected
   ✅ Application "appset-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-cephfs" undeployed
   ✅ Application "subscr-deploy-cephfs" unprotected
   ✅ Application "appset-deploy-rbd" unprotected
   ✅ Application "appset-deploy-rbd" undeployed
   ✅ Application "disapp-deploy-rbd" unprotected
   ✅ Application "subscr-deploy-rbd" undeployed
   ✅ Application "subscr-deploy-cephfs" undeployed
   ✅ Application "disapp-deploy-cephfs" undeployed
   ✅ Application "disapp-deploy-rbd" undeployed

🔎 Clean environment ...
   ✅ Environment cleaned

✅ passed (6 passed, 0 failed, 0 skipped)
```

### Test report

[test.tar.gz](https://github.com/user-attachments/files/19410221/test.tar.gz)

**Review by parikshithb — APPROVED** [review]
Nice, lgtm!
